"ui.background" = "white"
"ui.text" = "gray"
"ui.text.focus" = { fg = "white", bg = "blue" }
"ui.selection" = { fg = "white", bg = "light-blue" }
"ui.cursor" = { fg = "white", bg = "blue" }
"ui.linenr" = "gray"
"ui.linenr.selected" = "blue"
"ui.statusline" = "cyan"
"ui.statusline.normal" = { fg = "black", bg = "light-cyan"}
"ui.statusline.insert" = { fg = "black", bg = "red" }
"ui.statusline.select" = { fg = "black", bg = "green" }
"ui.statusline.inactive" = "light-gray"
"ui.popup" = "gray"
"ui.popup.header" = { fg = "white", bg = "cyan" }
"ui.window" = "black"
"ui.help" = "black"
"ui.gutter" = "light-gray"
"ui.gutter.selected" = "gray"

"ui.debug.active" = { bg = "magenta" }

"ui.menu" = "black"
"ui.menu.selected" = { fg = "white", bg = "cyan" }

"warning" = "light-yellow"
"error" = "light-red"
"info" = "light-green"
"hint" = "light-cyan"

"diagnostic" = { bg = "light-red", underline = { color = "red", style = "curl" } }
"diagnostic.hint" = { bg = "light-cyan", underline = { color = "light-cyan", style = "line" } }
"diagnostic.info" = { bg = "light-green", underline = { color = "light-green", style = "line" } } 
"diagnostic.warning" = { bg = "light-yellow", underline = { color = "light-yellow", style = "curl" } }
"diagnostic.error" = { bg = "light-red", underline = { color = "light-red", style = "curl" } }

"type" = "light-blue"
"type.builtin" = { fg = "light-blue", modifiers = ["italic"] }
"type.parameter" = "magenta"

"constant" = { fg = "red", underline = { color = "red", style = "line" } }
"constant.numeric" = "yellow"
"constant.builtin" = { fg = "red", modifiers = ["italic"] }

"string" = "green"
"string.special" = "red"

"comment" = "gray"

"variable" = "cyan"
"variable.builtin" = { fg = "cyan", modifiers = ["italic"] }
"variable.parameter" = "magenta"

"label" = "light-blue"

"punctuation" = "black"

"keyword" = { fg = "blue", modifiers = ["italic"] }
"keyword.control" = { fg = "red", modifiers = ["italic"] }

"function" = "cyan"
"function.builtin" = { fg = "cyan", modifiers = ["italic"] }

"tag" = "light-blue"
"tag.builtin" = { fg = "blue", modifiers = ["italic"] }

"namespace" = "red"

"markup" = "cyan"

"diff.plus" = { bg = "light-green" }
"diff.minus" = { bg = "light-red" }

[palette]
black = "#3B3B3B"
white = "#F0F8FF"

red = "#C998AE"
green = "#7FAD9C"
yellow = "#CFB886"
blue = "#56A0D1"
magenta = "#CBA0E3"
cyan = "#99BFD1"
gray = "#C2C2C2"

light-red = "#D6ABBC"
light-green = "#93B89F"
light-yellow = "#C4B290"
light-blue = "#7DB0D6"
light-magenta = "#C0A3DE"
light-cyan = "#98BECF"
light-gray = "#D4D4D4"
