"ui.background" = "white"
"ui.text" = "black"
"ui.text.focus" = { fg = "white", bg = "blue" }
"ui.selection" = { fg = "white", bg = "cyan" }
"ui.cursor" = { fg = "white", bg = "blue" }
"ui.cursor.insert" = { fg = "white", bg = "blue" }
"ui.cursor.match" = { fg = "white", bg = "maganta" }
"ui.linenr" = "gray"
"ui.linenr.selected" = "white"
"ui.statusline" = { fg = "white", bg = "cyan"}
"ui.statusline.normal" = { fg = "white", bg = "blue"}
"ui.statusline.insert" = { fg = "white", bg = "red" }
"ui.statusline.select" = { fg = "white", bg = "green" }
"ui.statusline.inactive" = "gray"
"ui.bufferline" = { fg = "white", bg = "cyan"}
"ui.bufferline.active" = { fg = "white", bg = "blue"}
"ui.bufferline.background" = { fg = "white", bg = "cyan"}
"ui.popup" = { fg = "black", bg = "white"}
"ui.popup.header" = { fg = "white", bg = "cyan" }
"ui.window" = { fg = "black", bg = "white"}
"ui.help" = "black"
"ui.gutter" = "gray"
"ui.gutter.selected" = { fg = "white", bg = "cyan"}

"ui.debug.active" = { bg = "magenta" }

"ui.menu" = "black"
"ui.menu.selected" = { fg = "white", bg = "cyan" }

"warning" = "yellow"
"error" = "red"
"info" = "green"
"hint" = "cyan"

"diagnostic" = { fg = "black", bg = "red", underline = { color = "red", style = "curl" } }
"diagnostic.hint" = { fg = "black", bg = "cyan", underline = { color = "cyan", style = "line" } }
"diagnostic.info" = { fg = "black", bg = "green", underline = { color = "green", style = "line" } } 
"diagnostic.warning" = { fg = "black", bg = "yellow", underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { fg = "black", bg = "red", underline = { color = "red", style = "curl" } }

"type" = "blue"
"type.builtin" = { fg = "blue", modifiers = ["italic"] }
"type.parameter" = "magenta"

"constant" = { fg = "red", underline = { color = "red", style = "line" } }
"constant.numeric" = "yellow"
"constant.builtin" = { fg = "red", modifiers = ["italic"] }

"string" = "green"
"string.special" = "red"

"comment" = "gray"

"variable" = "cyan"
"variable.builtin" = { fg = "cyan", modifiers = ["italic"] }
"variable.parameter" = "magenta"

"label" = "blue"

"punctuation" = "black"

"keyword" = { fg = "blue", modifiers = ["italic"] }
"keyword.control" = { fg = "red", modifiers = ["italic"] }

"function" = "cyan"
"function.builtin" = { fg = "cyan", modifiers = ["italic"] }
"constructor" = "magenta"

"tag" = "blue"
"tag.builtin" = { fg = "blue", modifiers = ["italic"] }

"namespace" = "red"

"markup" = "cyan"

"diff.plus" = { bg = "green" }
"diff.minus" = { bg = "red" }

[palette]
black = "#3B3B3B"
white = "#F0F8FF"

red = "#C998AE"
green = "#7FAD9C"
yellow = "#CFB886"
blue = "#56A0D1"
magenta = "#CBA0E3"
cyan = "#99BFD1"
gray = "#C2C2C2"

# light-red = "#D6ABBC"
# light-green = "#93B89F"
# light-yellow = "#C4B290"
# light-blue = "#7DB0D6"
# light-magenta = "#C0A3DE"
# light-cyan = "#98BECF"
# light-gray = "#D4D4D4"
