theme = "mizuiro"

[editor]
true-color = true
line-number = "relative"
bufferline = "always"
color-modes = true
mouse = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "bar"

[editor.whitespace.render]
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "·"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
"^" = "goto_line_start"
"$" = "goto_line_end"
