[font]
normal = {family = "IosevkaCustomAkwa Nerd Font", style = "regular"}

[window]
# opacity = 0.8

[colors]

[colors.primary]
foreground = "#4D4D4D"
background = "#F0F8FF"

[colors.normal]
black   = "#3B3B3B"
red     = "#C998AE"
green   = "#7FAD9C"
yellow  = "#CFB886"
blue    = "#56A0D1"
magenta = "#CBA0E3"
cyan    = "#99BFD1"
white   = "#C2C2C2"

[colors.bright]
black   = "#969696"
red     = "#D6ABBC"
green   = "#93B89F"
yellow  = "#C4B290"
blue    = "#7DB0D6"
magenta = "#C0A3DE"
cyan    = "#98BECF"
white   = "#D4D4D4"

[cursor]
style = {shape = "Beam", blink = "Never"}

[mouse]
bindings = [
    {mouse = "Right", mods = "Control", action = "Paste"},
    {mouse = "Middle", mods = "Control", action = "Copy"},
]
